### ISSUE TITLE
DOCKERFILE not installing via conda

### ISSUE THREAD

**Issue by bpstewar** [bpstewar/spfeas_zonal_Docker#1]
I am trying to install two libraries through CONDA in the dockerfile, and they don't seem to work
```
RUN ["/bin/bash", "-c", "source activate spfeasenv && conda install --name spfeasenv -c conda-forge geopandas -y"] 
RUN ["/bin/bash", "-c", "source activate spfeasenv && conda install --name spfeasenv rasterio -y"]
```
I cannot see any errors, but when I run the final script, it errors saying rasterio doesn't exist. HOWEVER, when I enter the docker and enter those conda install commands manually, they work fine.

**Comment by jgrss** [comment]
You have the activation lines commented in Dockerfile. Just to confirm, did you run it with or without the lines below?

```bash
ENTRYPOINT [ "/bin/bash", "-c" ]
CMD ["source activate spfeasenv && exec python run_spfeas_Zonal.py"]
```

**Comment by bpstewar** [comment]
I commented them out so I could enter the docker directly during testing - they are back in now

**Comment by bpstewar** [comment]
I figured out a solution - I installed geopandas using pip instead. However, I would still like to understand what the installation problem with conda was
